urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import PostListView, PostDetailView, PostUpdateView, PostDeleteView, PostCreateView
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.blog_index, name="blog_index"),
    path('', PostListView.as_view(), name='list'),
    path('add/', PostCreateView.as_view(), name='add'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='delete'),
]

models.py
from django.db import models
from django_quill.fields import QuillField
from django.urls import reverse
from django.contrib.auth.models import User

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    body = QuillField()
    
    def __str__(self):
        return self.title
    

    def get_absolute_url(self):
        return reverse('blog:list')

views.py
from django.shortcuts import render
from django.shortcuts import render, HttpResponse, redirect
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import Post

# Create your views here.
def blog_index(request):
    return render(request, 'blog/blog_index.html')

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'body']

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:list')

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)
    

class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'

class PostDetailView(UpdateView):
    model = Post
    fields = ['title', 'body', 'author']
    template_name = 'blog/post_detail.html'

templates/blog/blog_index.html
{% extends 'base.html' %}

{% block content %}
    <div class="w3-center" style="margin-inline: 630px;" >
        <div style="background-color: lightpink;
                    height: 876px;">
                        <h1>Blog</h1>
                        <i>Memories keeper</i>
                        <a href="{% url 'blog:list' %}">Post</a>
        </div>
    </div>

{% endblock %}

templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  
<div class="w3-center" style="margin-inline: 630px;" >
    <div style="background-color: lightpink;
                height: 876px;">
{% if request.user == post.author %}
<p>Are you sure you want to delete this post?</p>
<h3>{{ post.title }}</h3>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>
{% else %}
<p>User : {{user}}</p>
<p>You can't edit this page!</p>
{% endif %}  
    </div>
</div>
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}




<div class="w3-center" style="margin-inline: 630px;" >
    <div style="background-color: lightpink;
                height: 876px;">
{{ form.media }}

<h1 id="title">title</h1>

<div class="w3-theme-l5">
    <form action="" method="post">
        <p class="title">{{ form.title }}</p>
        {{ form.body }}
    </form>
</div>
<p>Author : {{ post.author }}</p>

<p>
    {% if user.is_authenticated and request.user == post.author %}
        <p><a href="{% url 'blog:update' post.id %}">Edit</a></p>
        <p><a href="{% url 'blog:delete' post.id %}">Delete</a></p>

    {% endif %}
</p>
    <script>
        var editable_elements = document.querySelectorAll("[contenteditable=true]");  
        editable_elements.forEach(function(element){
            element.contentEditable = 'false';
        })

        document.querySelector(".ql-toolbar").style.display = 'none';
        document.querySelector(".ql-container").style.border = 'none';

        let title = document.querySelector('#id_title').value;
        document.querySelector('#title').innerHTML = title;
        document.querySelector('.title').style.display = 'none';
    </script>

    </div>
</div>

{% endblock %}

templates/blog/post_form.html
{% extends 'base.html' %}

{% block content %}


<div class="w3-center" style="margin-inline: 630px;" >
    <div style="background-color: lightpink;
                height: 876px;">
{{ form.media }}
<div class="w3-container">
    <form action="" method="post">{% csrf_token %}
        <p>{{ form.title }}</p>
        <p>{{ form.body }}</p>
        <p><input type="submit" value="Post"></p>
        
    </form>
</div>

    </div>
</div>
{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="w3-center" style="margin-inline: 630px;" >
        <div style="background-color: lightpink;
                    height: 876px;">
    <h1>All Post</h1>
    {% if user.is_authenticated %}
    <p><a href="{% url 'blog:add' %}">New Post</a></p>
    {% endif %}
    
    {% for posts in object_list %}
        <p><a href="{% url 'blog:detail' pk=posts.id %}">{{ posts.title }}</a> : {{posts.author}}</p>
    {% endfor %}

        </div>
    </div>
{% endblock %}